### ISSUE TITLE
Upgrading pid-cwd

### ISSUE THREAD

**Issue by RkEclair** [LeanderFS/hypersamewd#7]
This extension is not supported to open a new tab with the path included some character such as CJK now.

This problem comes from the pid-cwd, so I fixed it at https://github.com/NeekSandhu/pid-cwd/issues/1 .

Could you upgrade the version of pid-cwd?

**Comment by LeanderFS** [comment]
Thanks for taking the time to raise this issue! I have updated the pid-cwd version to 1.2.0
